# Generated by Django 6.0.5 on 2026-05-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feature_sitestat_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Prayer for the St. Joseph Province Chapter 2027', help_text='The heading displayed on the prayer card', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='A Prayer of Hope, Mission & Renewal', help_text='Displayed below the title as a decorative tagline', max_length=300)),
                ('body', models.TextField(default="Heavenly Father,\n\nWe come before You with hearts full of gratitude and hope,\nas we prepare to gather in Chapter for the St. Joseph Province in 2027.\n\nGrant us, O Lord, the wisdom of St. Joseph —\nthat quiet, steadfast trust that discerns Your will in every season,\nand the courage to act upon it with humble obedience.\n\nBreathe into our assembly the fire of Your Holy Spirit,\nthat our deliberations may not be mere human striving,\nbut a listening — attentive, patient, and docile —\nto where You are calling our Province in this hour.\n\nMay our Chapter be a moment of grace:\na time to renew our Salesian consecration,\nto deepen our fraternal bonds,\nand to recommit ourselves to the young\nwho walk in darkness and await the light of Don Bosco's charism.\n\nBless each capitulant and all who serve in preparation.\nGuard our Province in unity, truth, and joy.\nLet our decisions bear fruit for generations to come,\nto the glory of Your name and the salvation of souls.\n\nWe ask this through Christ our Lord,\nin the company of Mary Help of Christians\nand our Father and Founder, St. John Bosco.\n\nAmen.", help_text='Full prayer text. Use blank lines to separate stanzas/paragraphs.')),
                ('prayer_intention', models.CharField(blank=True, default='For wisdom, unity, and the renewal of our Salesian mission.', help_text='Short intention line displayed at the bottom of the card', max_length=400)),
                ('author_attribution', models.CharField(blank=True, default='St. Joseph Province — Bangladesh', help_text='Attribution line at the foot of the prayer', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show this prayer on the website')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chapter Prayer',
                'verbose_name_plural': 'Chapter Prayer',
            },
        ),
    ]
