# Generated by Django 6.0.5 on 2026-05-12 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chapterprayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Calendar date for this chapter day')),
                ('day_label', models.CharField(help_text="Short label, e.g. 'Day 1 — Opening', 'Day 2 — Deliberations'", max_length=100)),
                ('theme', models.CharField(blank=True, help_text='Optional theme or subtitle for the day', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Schedule Day',
                'verbose_name_plural': 'Schedule Days',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(help_text='Start time (24-hour or AM/PM)')),
                ('time_end', models.TimeField(blank=True, help_text='End time (optional)', null=True)),
                ('title', models.CharField(help_text='Programme title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Details, agenda notes, etc.')),
                ('location', models.CharField(blank=True, help_text='Room, venue, or place', max_length=200)),
                ('speaker', models.CharField(blank=True, help_text='Speaker / presider name(s)', max_length=200)),
                ('category', models.CharField(choices=[('liturgy', '🙏 Liturgy / Prayer'), ('session', '📋 Session / Working Group'), ('keynote', '🎤 Keynote / Talk'), ('meal', '🍽️ Meal / Refreshment'), ('break', '☕ Break'), ('social', '🤝 Social / Recreation'), ('travel', '🚌 Travel / Transfer'), ('other', '📌 Other')], default='session', max_length=20)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Pin this event as important (shown with extra emphasis)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.scheduleday')),
            ],
            options={
                'verbose_name': 'Schedule Event',
                'verbose_name_plural': 'Schedule Events',
                'ordering': ['order', 'time_start'],
            },
        ),
    ]
