# Generated by Django 6.0.5 on 2026-05-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scheduleday_scheduleevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SJP Chapter Hub', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Upload the official chapter logo', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Upload the site favicon (.ico or .png)', null=True, upload_to='site/')),
                ('footer_text', models.TextField(blank=True, help_text='Optional text for the footer description')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
