# Generated by Django 6.0.5 on 2026-07-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose whether this slide displays an image or a video', max_length=10),
        ),
        migrations.AddField(
            model_name='homeslider',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file (mp4, webm) instead of or in addition to an image', null=True, upload_to='sliders/'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file (used as slide background or video thumbnail/poster)', null=True, upload_to='sliders/'),
        ),
    ]
