# Generated by Django 6.0.5 on 2026-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_homeslider_media_type_homeslider_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterprayer',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Upload back side image of the prayer card', null=True, upload_to='prayer/'),
        ),
        migrations.AddField(
            model_name='chapterprayer',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Upload front side image of the prayer card', null=True, upload_to='prayer/'),
        ),
    ]
