# Generated by Django 6.0.5 on 2026-07-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chapterprayer_back_image_chapterprayer_front_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterprayer',
            name='title',
            field=models.CharField(blank=True, default='Prayer for the St. Joseph Province Chapter 2027', help_text='The heading displayed on the prayer card (optional)', max_length=200),
        ),
    ]
