# Generated by Django 6.0.5 on 2026-07-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_chapterprayer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
